In [1]:
# libs
import pandas as pd
import numpy as np
import time
import os
import sys

sys.path.insert(1, '/Users/ninja/Dropbox/analytics/codes/utility')
import data

# plotting setting
from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set_style('darkgrid', {'axes.facecolor': '.9'})
sns.set_palette(palette='deep')
sns_c = sns.color_palette(palette='deep')

# display setting
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from IPython.display import display
np.set_printoptions(precision=12)

In [95]:
nb_fcst_qtr  = 10
nb_timed_qtr = 9
nrow = 1

ans = np.zeros((nrow*(nb_fcst_qtr+nb_timed_qtr-1),nb_fcst_qtr))
# ans
loan_id = np.array([1]*nb_fcst_qtr)
data = np.arange(1,10).reshape(nb_fcst_qtr,1)/10
qtr_no = np.arange(1,nb_fcst_qtr+1).reshape(nb_fcst_qtr,1)
data = np.hstack((loan_id,qtr_no,data))
# data
# weight = np.arange(0.1,1,0.1).reshape(9,1)
# weight /= sum(weight)
# # weight

multi=np.multiply(data[:,1],weight)
for qtr_no in range(1,10):
    i = range(qtr_no-1,qtr_no+nb_timed_qtr-1)
    j = [qtr_no-1]
    ans[np.ix_(i,j)] = multi[qtr_no-1,:].reshape(nb_timed_qtr,1)
pd.DataFrame(ans)

0         1         2         3         4         5         6  \
0   0.002222  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.004444  0.004444  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.006667  0.008889  0.006667  0.000000  0.000000  0.000000  0.000000   
3   0.008889  0.013333  0.013333  0.008889  0.000000  0.000000  0.000000   
4   0.011111  0.017778  0.020000  0.017778  0.011111  0.000000  0.000000   
5   0.013333  0.022222  0.026667  0.026667  0.022222  0.013333  0.000000   
6   0.015556  0.026667  0.033333  0.035556  0.033333  0.026667  0.015556   
7   0.017778  0.031111  0.040000  0.044444  0.044444  0.040000  0.031111   
8   0.020000  0.035556  0.046667  0.053333  0.055556  0.053333  0.046667   
9   0.000000  0.040000  0.053333  0.062222  0.066667  0.066667  0.062222   
10  0.000000  0.000000  0.060000  0.071111  0.077778  0.080000  0.077778   
11  0.000000  0.000000  0.000000  0.080000  0.088889  0.093333  0.093333   
12  0.000000  0.000000  0.000000  0.000000  0.100000  0.106667  0.108889   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.120000  0.124444   
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.140000   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

           7     8  
0   0.000000  0.00  
1   0.000000  0.00  
2   0.000000  0.00  
3   0.000000  0.00  
4   0.000000  0.00  
5   0.000000  0.00  
6   0.000000  0.00  
7   0.017778  0.00  
8   0.035556  0.02  
9   0.053333  0.04  
10  0.071111  0.06  
11  0.088889  0.08  
12  0.106667  0.10  
13  0.124444  0.12  
14  0.142222  0.14  
15  0.160000  0.16  
16  0.000000  0.18

In [149]:
# CECL: flex qtr_no
nb_fcst_qtr  = 10
nb_timed_qtr = 9
nrow = 1
loan_id = np.array([1]*nb_fcst_qtr).reshape(nb_fcst_qtr,1)
data = np.arange(1,nb_fcst_qtr+1).reshape(nb_fcst_qtr,1)/10
qtr_no = np.arange(1,nb_fcst_qtr+1).reshape(nb_fcst_qtr,1)
l1 = np.hstack((loan_id,qtr_no,data))
l2 = l1[:3,:].copy()
l2[:,0] = 2
data = np.vstack((l1,l2))
data = np.append(data, np.zeros([len(data),1]), 1)
data

weight = np.array([0.25,0.15,0.25,0.2,0.05,0.05,0.05,0,0])
weight

loss_ary  = np.zeros(nb_timed_qtr)
loan_prev = data[0,0] 
for i in range(data.shape[0]):         
    if data[i,0] != loan_prev:
        loss_ary  = np.zeros(nb_timed_qtr)
    loss_ary = np.insert(loss_ary, 0, data[i,2])
    data[i,3] = np.inner(loss_ary[:nb_timed_qtr],weight)
    loan_prev = data[i,0]

data
# nrow = data.shape[0]
# out  = np.zeros((nrow*9,3)) 
# timed_qtr = np.arange(0,9)
# for i in range(nrow):
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,0] = data[i,0]
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,1] = data[i,1] + timed_qtr
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,2] = data[i,2] * timed_w
# out

array([[ 1. ,  1. ,  0.1,  0. ],
       [ 1. ,  2. ,  0.2,  0. ],
       [ 1. ,  3. ,  0.3,  0. ],
       [ 1. ,  4. ,  0.4,  0. ],
       [ 1. ,  5. ,  0.5,  0. ],
       [ 1. ,  6. ,  0.6,  0. ],
       [ 1. ,  7. ,  0.7,  0. ],
       [ 1. ,  8. ,  0.8,  0. ],
       [ 1. ,  9. ,  0.9,  0. ],
       [ 1. , 10. ,  1. ,  0. ],
       [ 2. ,  1. ,  0.1,  0. ],
       [ 2. ,  2. ,  0.2,  0. ],
       [ 2. ,  3. ,  0.3,  0. ]])

array([0.25, 0.15, 0.25, 0.2 , 0.05, 0.05, 0.05, 0.  , 0.  ])

array([[ 1.   ,  1.   ,  0.1  ,  0.025],
       [ 1.   ,  2.   ,  0.2  ,  0.065],
       [ 1.   ,  3.   ,  0.3  ,  0.13 ],
       [ 1.   ,  4.   ,  0.4  ,  0.215],
       [ 1.   ,  5.   ,  0.5  ,  0.305],
       [ 1.   ,  6.   ,  0.6  ,  0.4  ],
       [ 1.   ,  7.   ,  0.7  ,  0.5  ],
       [ 1.   ,  8.   ,  0.8  ,  0.6  ],
       [ 1.   ,  9.   ,  0.9  ,  0.7  ],
       [ 1.   , 10.   ,  1.   ,  0.8  ],
       [ 2.   ,  1.   ,  0.1  ,  0.025],
       [ 2.   ,  2.   ,  0.2  ,  0.065],
       [ 2.   ,  3.   ,  0.3  ,  0.13 ]])

In [146]:
data = np.append(data, np.zeros([len(data),1]), 1)
data.shape


(13, 5)