In [1]:
# libs
import pandas as pd
import numpy as np
import time
import os
import sys

sys.path.insert(1, '/Users/ninja/Dropbox/analytics/codes/utility')
import data

# plotting setting
from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set_style('darkgrid', {'axes.facecolor': '.9'})
sns.set_palette(palette='deep')
sns_c = sns.color_palette(palette='deep')

# display setting
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from IPython.display import display
np.set_printoptions(precision=12)

In [4]:
# CECL: flex qtr_no
nb_fcst_qtr  = 10
nb_timed_qtr = 9
nrow = 1
loan_id = np.array([1]*nb_fcst_qtr).reshape(nb_fcst_qtr,1)
data = np.arange(1,nb_fcst_qtr+1).reshape(nb_fcst_qtr,1)/10
qtr_no = np.arange(1,nb_fcst_qtr+1).reshape(nb_fcst_qtr,1)
l1 = np.hstack((loan_id,qtr_no,data))
l2 = l1[:3,:].copy()
l2[:,0] = 2
data = np.vstack((l1,l2))
data = np.append(data, np.zeros([len(data),1]), 1)
data

weight = np.array([0.25,0.15,0.25,0.2,0.05,0.05,0.05,0,0])
weight

def time_loss(data, weight, nb_timed_qtr):
    loss_ary  = np.zeros(nb_timed_qtr)
    loan_prev = data[0,0] 
    for i in range(data.shape[0]):         
        if data[i,0] != loan_prev:
            loss_ary  = np.zeros(nb_timed_qtr)
        loss_ary = np.insert(loss_ary, 0, data[i,2])
        data[i,3] = np.inner(loss_ary[:nb_timed_qtr],weight)
        loan_prev = data[i,0]
    return data

time_loss(data, weight, nb_timed_qtr)

array([[ 1. ,  1. ,  0.1,  0. ],
       [ 1. ,  2. ,  0.2,  0. ],
       [ 1. ,  3. ,  0.3,  0. ],
       [ 1. ,  4. ,  0.4,  0. ],
       [ 1. ,  5. ,  0.5,  0. ],
       [ 1. ,  6. ,  0.6,  0. ],
       [ 1. ,  7. ,  0.7,  0. ],
       [ 1. ,  8. ,  0.8,  0. ],
       [ 1. ,  9. ,  0.9,  0. ],
       [ 1. , 10. ,  1. ,  0. ],
       [ 2. ,  1. ,  0.1,  0. ],
       [ 2. ,  2. ,  0.2,  0. ],
       [ 2. ,  3. ,  0.3,  0. ]])

array([0.25, 0.15, 0.25, 0.2 , 0.05, 0.05, 0.05, 0.  , 0.  ])

array([[ 1.   ,  1.   ,  0.1  ,  0.025],
       [ 1.   ,  2.   ,  0.2  ,  0.065],
       [ 1.   ,  3.   ,  0.3  ,  0.13 ],
       [ 1.   ,  4.   ,  0.4  ,  0.215],
       [ 1.   ,  5.   ,  0.5  ,  0.305],
       [ 1.   ,  6.   ,  0.6  ,  0.4  ],
       [ 1.   ,  7.   ,  0.7  ,  0.5  ],
       [ 1.   ,  8.   ,  0.8  ,  0.6  ],
       [ 1.   ,  9.   ,  0.9  ,  0.7  ],
       [ 1.   , 10.   ,  1.   ,  0.8  ],
       [ 2.   ,  1.   ,  0.1  ,  0.025],
       [ 2.   ,  2.   ,  0.2  ,  0.065],
       [ 2.   ,  3.   ,  0.3  ,  0.13 ]])

In [ ]:
# nrow = data.shape[0]
# out  = np.zeros((nrow*9,3)) 
# timed_qtr = np.arange(0,9)
# for i in range(nrow):
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,0] = data[i,0]
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,1] = data[i,1] + timed_qtr
#     out[i*nb_timed_qtr:(i+1)*nb_timed_qtr,2] = data[i,2] * timed_w
# out